# Experiments in using KNN to predict performance
# Based on ideas from Nate Silver's PECOTA: https://en.wikipedia.org/wiki/PECOTA

iris <- read.csv(url("http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"), header = FALSE)
names(iris) <- c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width", "Species")

library(ggvis)
iris %>%
    ggvis( ~ Sepal.Length, ~ Sepal.Width, fill = ~Species) %>%
    layer_points()

# Using a factor for fill is cool. I can do this for position players scatter plots of their stats

# This is a cool command that counts factors
table(iris$Species)

summary(iris)

# Classification package
library(class)

normalize <- function(x) {
    num <- x - min(x)
    denom <- max(x) - min(x)
    return (num/denom)
}

iris_norm <- as.data.frame(lapply(iris[1:4], normalize))

# Now look: all values for each column are between 0 and 1
summary(iris_norm)

# Now generate the training and test data sets
# I want 67 / 33 split between training and test data

# Deterministic random number generators ... yay
set.seed(4242)

# This generates a vector such that there is a 67/33 probability of 1s vs. 2s
ind <- sample(2, nrow(iris), replace = TRUE, prob = (c(0.67, 0.33)))

# Verify
table(ind)

# Now perform slicing

iris.training <- iris[ind == 1, 1:4]
iris.testing <- iris[ind == 2, 1:4]

# Labels are species, so separate them into separate data structures

iris.training.labels <- iris[ind == 1, 5]
iris.testing.labels <- iris[ind == 2, 5]

# Now we have the training and test data sets, now time to apply knn

iris.results <- knn(train = iris.training, test = iris.testing, cl = iris.training.labels, k = 3)

iris.results

library(gmodels)
CrossTable(x = iris.testing.labels, y = iris.results, prop.chisq = FALSE)


# Now how do I use the knn model generated by iris.results? i.e., given Sepal.Length, Sepal.Width, Petal.Length, Petal.Width ???

